### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by timche** [redux-utilities/flux-standard-action#125]
https://github.com/redux-utilities/flux-standard-action#looking-for-maintainers

**Comment by schalkventer** [comment]
Hey @timche. I use FSA quite a lot with `useReducer` in React. I'm happy to chat about how I can help out with maintenance if you are interested?

**Comment by timche** [comment]
@schalkventer sure thing! Just pop me an email with [your details](https://github.com/redux-utilities/flux-standard-action#looking-for-maintainers) so we can discuss your options :)
