### ISSUE TITLE
Action creator example

### ISSUE THREAD

**Issue by everking** [redux-utilities/flux-standard-action#35]
Is it safe to assume that action creators should always have the following signature?

```
export function someAction(payload, error, meta) {
    return {
        type: SOME_ACTION,
        payload,
        error,
        meta
    };
};
```

**Comment by yangmillstheory** [comment]
Some of the keys above are [optional](https://github.com/acdlite/flux-standard-action#actions) in an FSA - `payload`, `error`, and `meta`, for example.

Your action creator will always have these keys, however.

```js
const [ foo, bar ] = [ 1, undefined ]

console.log({ foo, bar }) // { foo: 1, bar: undefined }
```

So it's not a valid assumption, as there exist action creators which output actions without some of the keys mentioned above.

**Comment by everking** [comment]
Thanks for the response @yangmillstheory.

What I meant was the parameter names that it will always have either none, or restricted to the following parameter names `payload`, `error` or `meta`.

    function someAction()
    function someAction(payload)
    function someAction(payload, error)
    function someAction(payload, error, meta)

So the following would be invalid/non-compliant:

    function someAction(myOwnParam)
    function someAction(myOwnParam, anotherParam)

**Comment by everking** [comment]
@yangmillstheory @acdlite - any thoughts?

**Comment by JaKXz** [comment]
I believe this is taken care of by using redux-actions. Closing as stale.
