### ISSUE TITLE
Suggestion - Provide class/factory function as default export

### ISSUE THREAD

**Issue by robgraeber** [redux-utilities/flux-standard-action#80]
Hi there, have you ever considered providing a basic class/factory function as the default export for the package? It'd provide some syntactic sugar when writing your actions. I imagine the usage would be kinda like this:

```js 
import Action from 'flux-standard-action'

export function setUsername(username) {
  return new Action('SET_USERNAME', username);
}
```

If you're open to it, I can make the PR. Thanks!

**Comment by JaKXz** [comment]
Hi @robgraeber thanks for the suggestion! I think https://github.com/reduxactions/redux-actions is what you're thinking/looking for. :)

**Comment by robgraeber** [comment]
@JaKXz Afaik redux-actions is different, it creates action creators and reducers. Versus I'm proposing an Action class/factory function to go along with the typescript interface definition.

**Comment by JaKXz** [comment]
From your usage example, the constructor takes the action `type` and the `payload`, and I assume returns the action object that you would dispatch.

You can achieve this with redux-actions:

```js
// in setUsername.js
import { createAction } from 'redux-actions'

export default createAction('SET_USERNAME', username => username)
```

You can see more examples [here](https://redux-actions.js.org/docs/api/createAction.html#createaction) - I think your suggestion is very valid, but I don't think that creating duplication here is necessary.

This repo is really meant to serve as documentation for what FSAs are. `redux-actions` promises to be FSA compliant.

**Comment by robgraeber** [comment]
@JaKXz My 2 cents: I gave it a try and I thought redux-actions ended up clunkier for what's conceptually a very simple task and didn't autocomplete as well for VSCode at least.

e.g.
```js
export function sendUsernameUpdate(newUsername, currentUsername) {
  return new Action(SEND_USERNAME_UPDATE, {newUsername, currentUsername});
}

vs

export const sendUsernameUpdate = ReduxActions.createAction(
  SEND_USERNAME_UPDATE,
  (newUsername, currentUsername) => ({newUsername, currentUsername})
);
```

**Comment by unional** [comment]
You can create one pretty easily.
For example: https://github.com/unional/fsa-emitter/blob/master/src/createActionCreator.ts

**Comment by JaKXz** [comment]
I'm going to mark this as closed for now. `redux-actions` is a great standard, but one size might not fit all.
